# Changes here will be overwritten by Copier
_commit: v0.1.1
_src_path: gh:igembitsgoa/igem-wiki-starter
author: Pranav Ballaney
email: ballaneypranav@gmail.com
iGEM_team_code: BITSPilani-Goa_India
iGEM_team_name: BITS Goa
year: 2020